//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int id { get; set; }
        public string FCs { get; set; }
        public string name_hotel { get; set; }
        public System.DateTime date_of_entry { get; set; }
        public System.DateTime departure_date { get; set; }
        public int number_of_room { get; set; }
        public string phone_number { get; set; }
    }
}
