//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public int id { get; set; }
        public string name_hotel { get; set; }
        public int number_room { get; set; }
        public int price { get; set; }
        public string Employment { get; set; }
        public System.DateTime departure_date { get; set; }
    }
}
